// <auto-generated />
using System;
using Loggit.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Loggit.Database.Migrations
{
    [DbContext(typeof(LoggitDbContext))]
    partial class LoggitDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Loggit.Entities.Events.LandingEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AircraftName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AirportName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PilotName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Landings");
                });

            modelBuilder.Entity("Loggit.Entities.Events.TakeoffEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AircraftName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AirportName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PilotName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Takeoffs");
                });
#pragma warning restore 612, 618
        }
    }
}
